import { Analytics } from "@vercel/analytics/next";
import type { Metadata } from "next";
import { Inter, Martian_Mono } from "next/font/google";
import { AuthHashRescue } from "~/components/auth-hash-rescue";
import { siteUrl } from "~/lib/site";
import { ThemeProvider } from "./theme-provider";
import "./globals.css";

/* Archivo, on both its axes, is the whole sans.
 *
 * It replaces Poppins, which was the previous display face and half the reason
 * four people read this site as machine-made: a geometric sans off the same
 * shortlist as Inter and Roboto, drawn to have no opinion.
 *
 * Archivo is a grotesque built for print at small sizes and for signage at
 * large ones, and its variable release carries a width axis as well as a
 * weight one. That is why it can be the only sans here: display type sets
 * condensed and heavy, running text sets normal and light, and the distance
 * between those two is a real typographic contrast rather than two weights of
 * the same picture. One family, one request, both jobs.
 *
 * `axes: ["wdth"]` is what keeps the width axis; without it Next ships the
 * weight axis alone and every condensed heading silently sets at normal
 * width. The italic is loaded because the headline uses it as a second voice:
 * the phrases the page marks are set italic as well as coloured, so the
 * emphasis survives being read in greyscale. */
/* Inter, the whole interface.
 *
 * Named in the brief, and the variable cut so weight is a continuous axis
 * rather than four downloads: display sits at 600-700, section headers at 600,
 * body at 400, and the steps between them are what carries hierarchy here
 * instead of size alone.
 *
 * `cv11` gives the single-storey l and the straight-tailed a, which is what
 * stops Inter at large sizes reading as the browser default. */
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});


/* Martian Mono carries the timecodes, cue labels and status lines.
 *
 * A monospace here is not a costume for "technical" — the page is laid out as
 * a broadcast running order, and every figure in it is a measurement that has
 * to stay in column as it counts: elapsed time, duration, word position. That
 * is the job monospace exists for. Martian Mono is drawn wide and slightly
 * mechanical, which reads as instrument rather than as code editor. */
const martianMono = Martian_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

const DIRECTION_CONTRACT = `<!--
seed 8e7cc5c5

THESIS: this product marks you while you are still talking, so the page marks
you while you are still reading it. It refuses the category arrangement — hero
claim, three feature cards, a screenshot — because a screenshot of live
marking is the one thing that cannot show live marking.

OWN-WORLD: the as-live broadcast script. Photocopy-grey stock, hard black
hairlines and no card edges anywhere, a monospaced timecode gutter running the
full height, Archivo condensed and heavy for display against Archivo light for
running text, ultramarine at page scale rather than as an accent, and green /
red / grey reserved for what they mean inside a transcript.

STORY: you arrive mid-transmission. Something is being said and marked in
front of you before you have read a word of copy. You understand that speaking
is the input and that the marking is claim by claim, you believe it because you
watched it happen rather than being told, and you cue your own.

FIRST VIEWPORT: full-bleed script. Timecode column hard left, spoken lines
arriving right of it at display scale and being wiped green, red or grey as
they land. The product name sits small in the masthead rule; the primary
action is an ultramarine cue block inline in the script, not floating above it.

FORM: the as-live transmission script, candidate 3 of the grounded list,
seed key 8e7cc5c5.

FINISH: unreviewed and undocumented is unfinished; this build ends with the
finish review, the verdict, and DESIGN.md
-->`;

const TITLE = "Explainaloud";
const DESCRIPTION =
  "Explain it back out loud and know exactly when you actually understand it.";

export const metadata: Metadata = {
  // Resolves the relative Open Graph and Twitter image paths below to absolute
  // URLs, which those crawlers require. See `siteUrl` for where the host comes
  // from — deliberately not from anything written down in this repo.
  metadataBase: new URL(siteUrl()),
  title: TITLE,
  description: DESCRIPTION,
  applicationName: TITLE,
  // Without these a shared link renders as a bare URL — no title, no image, no
  // description — in Slack, iMessage, Discord and every social preview. The
  // image itself is generated by `opengraph-image.tsx` from the same brand mark
  // as the favicon, so there is one source of truth for the shape.
  openGraph: {
    type: "website",
    siteName: TITLE,
    title: TITLE,
    description: DESCRIPTION,
    // Relative on purpose: `metadataBase` makes it absolute against whatever
    // host this deployment is actually serving from.
    url: "/",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning data-scroll-behavior="smooth">
      <body className={`${inter.variable} ${martianMono.variable} font-sans`}>
        {/* The direction this design is under contract to, emitted as a real
            HTML comment so it survives the production build and can be read
            off the served page rather than taken on trust from a source file
            nobody opens. `hidden` keeps the wrapper out of the layout; the
            comment inside it is the payload. */}
        {/* biome-ignore lint/security/noDangerouslySetInnerHtml: a fixed
            string constant with no interpolation, and the only way React
            renders a comment node at all. */}
        <div hidden dangerouslySetInnerHTML={{ __html: DIRECTION_CONTRACT }} />
        <ThemeProvider>{children}</ThemeProvider>
        {/* At the root because an emailed link lands wherever the project's
            Site URL points, and a session in the URL fragment is invisible to
            every server route. Renders nothing. */}
        <AuthHashRescue />
        <Analytics />
      </body>
    </html>
  );
}
