import { Analytics } from "@vercel/analytics/next";
import type { Metadata } from "next";
import { Geist_Mono, Instrument_Serif, Poppins } from "next/font/google";
import { siteUrl } from "~/lib/site";
import { ThemeProvider } from "./theme-provider";
import "./globals.css";

/* Three weights, not four. Nothing in the app uses `font-bold`, so 700 was a
   whole extra face fetched on every first load and never drawn. */
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-sans",
});

/* Mono is used only for section eyebrows and stat labels — the small tracked
   uppercase type that gives the page its editorial rhythm. */
const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

/* Display serif, used only for the accented word in a headline. One italic
   serif word against the geometric sans is the whole contrast — using it for
   more than that would flatten the effect. */
const instrumentSerif = Instrument_Serif({
  subsets: ["latin"],
  weight: "400",
  style: ["normal", "italic"],
  variable: "--font-display",
});

const TITLE = "Explainaloud";
const DESCRIPTION =
  "Explain it back out loud and know exactly when you actually understand it.";

export const metadata: Metadata = {
  // Resolves the relative Open Graph and Twitter image paths below to absolute
  // URLs, which those crawlers require. See `siteUrl` for where the host comes
  // from — deliberately not from anything written down in this repo.
  metadataBase: new URL(siteUrl()),
  title: TITLE,
  description: DESCRIPTION,
  applicationName: TITLE,
  // Without these a shared link renders as a bare URL — no title, no image, no
  // description — in Slack, iMessage, Discord and every social preview. The
  // image itself is generated by `opengraph-image.tsx` from the same brand mark
  // as the favicon, so there is one source of truth for the shape.
  openGraph: {
    type: "website",
    siteName: TITLE,
    title: TITLE,
    description: DESCRIPTION,
    // Relative on purpose: `metadataBase` makes it absolute against whatever
    // host this deployment is actually serving from.
    url: "/",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning data-scroll-behavior="smooth">
      <body
        className={`${poppins.variable} ${geistMono.variable} ${instrumentSerif.variable} font-sans`}
      >
        <ThemeProvider>{children}</ThemeProvider>
        <Analytics />
      </body>
    </html>
  );
}
